

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Airport.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class AirportEntities : DbContext
{
    public AirportEntities()
        : base("name=AirportEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Airlines> Airlines { get; set; }

    public virtual DbSet<Airplane> Airplane { get; set; }

    public virtual DbSet<Airports> Airports { get; set; }

    public virtual DbSet<Bagage> Bagage { get; set; }

    public virtual DbSet<Bookings> Bookings { get; set; }

    public virtual DbSet<BookingsStatus> BookingsStatus { get; set; }

    public virtual DbSet<BookingTickets> BookingTickets { get; set; }

    public virtual DbSet<Flights> Flights { get; set; }

    public virtual DbSet<FormOfPayments> FormOfPayments { get; set; }

    public virtual DbSet<Gates> Gates { get; set; }

    public virtual DbSet<Registration> Registration { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    public virtual DbSet<StatusGate> StatusGate { get; set; }

    public virtual DbSet<StatusRegistration> StatusRegistration { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<TicketsSelling> TicketsSelling { get; set; }

    public virtual DbSet<User> User { get; set; }

}

}

